---
apiVersion: v1
kind: Service
metadata:
   name: golang-app-service
   namespace: demo-ops
spec:
  type: LoadBalancer
  ports:
  - port: 8000
    targetPort: http
    protocol: TCP
  selector:
    app: golang-app
